### ISSUE TITLE
Photometric grids should be specified as part of Star objects, not Observer

### ISSUE THREAD

**Issue by rhdtownsend** [aaronesque/gyre-lc#15]
As currently configured, the grid file is specified during the Observer construction, when in fact it should be part of the Star construction.

Also, rather than providing a filename for the grid, the user should provide a PhotGrid instance. That way, it's up to the user how and from where they get the grid.

The workflow would then look like this:

```
# Create Photgrid object
pg = pymsg.load_photgrid_from_specgrid('sg-demo.h5', 'pb-kepler.h5')

# Create Star objects
Aa = lc.Star(mesa_model='iOri-Aa.mesa', gyre_model='iOri-Aa-response.h5', photgrid=pg)
Ab = lc.Star(mesa_model='iOri-Ab.mesa', gyre_model='iOri-Ab-response.h5', photgrid=pg)
```

**Comment by aaronesque** [comment]
In fact, this will also address the issue I'm having with autodocs not working with readthedocs. Once I fix this, I'll explain the problem more thoroughly.
